# .streamlit/secrets.toml

[acrcloud]
access_key = "71ca748d95cb94fece21483bb2269aef"
access_secret = "pyX6hVKYHv9o9ZHvJtwFJp14BL3OEDEeSWhHc3ni"
req_url = "https://identify-ap-southeast-1.acrcloud.com/v1/identify"

[musixmatch]
api_key = "78511c49b3msh2f58007da81da20p16ab40jsn70bc07dee00c"
api_host = "musixmatch-lyrics-songs.p.rapidapi.com"
